# Site settings
title: "Conny Lundgren"
email: conny.lundgren@gmail.com
description: "I'm a Product Manager, Developer and Agile Practicioner based in Malmö, Sweden."
baseurl: ""
url: "http://refactor.se"
twitter_username: connylundgren
github_username:  connylundgren
facebook_username:  lundgren.conny
linkedin_username: connylundgren

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
