# Site settings
title: refactor
email: conny.lundgren@gmail.com
description: "TODO: CHANGE! On Agile, Development, Mobile, Technology and life in general."
baseurl: ""
url: "http://refactor.se"
twitter_username: connylundgren
github_username:  connylundgren
facebook_username:  lundgren.conny
linkedin_username: connylundgren

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
